name: build-with-plugins
description: Build desktop binaries
inputs:
  platform:
    description: General target platform name (windows)
    required: true
  platform-short:
    description: General target platform short name (win)
    required: true
  runtime:
    description: Target platform runtime (win-x64)
    required: true
  build-version:
    description: Build or release version (0.0.1)
    required: true
runs:
  using: composite
  steps:
    - name: Build Core app package
      shell: bash
      run: |
        dotnet publish \
        Core/Cosmos.DataTransfer.Core/Cosmos.DataTransfer.Core.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }} \
        --self-contained true \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=true \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Build Cosmos Extension
      shell: bash
      run: |
        dotnet publish \
        Extensions/Cosmos/Cosmos.DataTransfer.CosmosExtension/Cosmos.DataTransfer.CosmosExtension.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }}/Extensions \
        --self-contained false \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=false \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Build JSON Extension
      shell: bash
      run: |
        dotnet publish \
        Extensions/Json/Cosmos.DataTransfer.JsonExtension/Cosmos.DataTransfer.JsonExtension.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }}/Extensions \
        --self-contained false \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=false \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Build Azure Table Extension
      shell: bash
      run: |
        dotnet publish \
        Extensions/AzureTableAPI/Cosmos.DataTransfer.AzureTableAPIExtension/Cosmos.DataTransfer.AzureTableAPIExtension.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }}/Extensions \
        --self-contained false \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=false \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Build Mongo Extension
      shell: bash
      run: |
        dotnet publish \
        Extensions/Mongo/Cosmos.DataTransfer.MongoExtension/Cosmos.DataTransfer.MongoExtension.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }}/Extensions \
        --self-contained false \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=false \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Build SQL Server Extension
      shell: bash
      run: |
        dotnet publish \
        Extensions/SqlServer/Cosmos.DataTransfer.SqlServerExtension/Cosmos.DataTransfer.SqlServerExtension.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }}/Extensions \
        --self-contained false \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=false \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Build Parquet Extension
      shell: bash
      run: |
        dotnet publish \
        Extensions/Parquet/Cosmos.DataTransfer.ParquetExtension/Cosmos.DataTransfer.ParquetExtension.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }}/Extensions \
        --self-contained false \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=false \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Build Cognitive Search Extension
      shell: bash
      run: |
        dotnet publish \
        Extensions/CognitiveSearch/Cosmos.DataTransfer.CognitiveSearchExtension/Cosmos.DataTransfer.CognitiveSearchExtension.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }}/Extensions \
        --self-contained false \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=false \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Build CSV Extension
      shell: bash
      run: |
        dotnet publish \
        Extensions/Csv/Cosmos.DataTransfer.CsvExtension/Cosmos.DataTransfer.CsvExtension.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }}/Extensions \
        --self-contained false \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=false \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Build PostgreSQL Extension
      shell: bash
      run: |
        dotnet publish \
        Extensions/PostgreSQL/Cosmos.DataTransfer.PostgresqlExtension.csproj \
        --configuration Release \
        --output ${{ inputs.platform-short }}/Extensions \
        --self-contained false \
        --runtime ${{ inputs.runtime }} \
        -p:PublishSingleFile=false \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishReadyToRun=false \
        -p:PublishTrimmed=false \
        -p:Version=${{ inputs.build-version }}
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.platform }}-package
        path: ${{ inputs.platform-short }}/
