name: Build desktop binaries
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-package:
    name: Build self-contained executables
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - name: Check .NET version
        run: dotnet --version
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Execute Action build-with-plugins for MacOS
        uses: ./.github/actions/build-with-plugins
        id: build-with-plugins-mac
        with:
          platform: mac
          platform-short: mac
          runtime: osx-x64
          build-version: 0.0.${{ github.run_number }}
      - name: Execute Action build-with-plugins for Linux
        uses: ./.github/actions/build-with-plugins
        id: build-with-plugins-linux
        with:
          platform: linux
          platform-short: linux
          runtime: linux-x64
          build-version: 0.0.${{ github.run_number }}
  build-package-win:
    name: Build self-contained Windows executables
    runs-on: windows-2022
    steps:
      - name: Check .NET version
        run: dotnet --version
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Execute Action build-with-plugins for Windows
        uses: ./.github/actions/build-with-plugins
        id: build-with-plugins-win
        with:
          platform: windows
          platform-short: win
          runtime: win-x64
          build-version: 0.0.${{ github.run_number }}
      - name: Build Windows desktop package
        shell: bash
        run: |
          dotnet publish \
          App/Cosmos.DataTransfer.App.Windows/Cosmos.DataTransfer.App.Windows.csproj \
          --configuration Release \
          --output win \
          --self-contained true \
          --runtime win-x64 \
          -p:PublishSingleFile=true \
          -p:DebugType=embedded \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:EnableCompressionInSingleFile=true \
          -p:Version=0.0.${{ github.run_number }}
      - name: Upload gui package
        uses: actions/upload-artifact@v3
        with:
          name: windows-gui-package
          path: win/
