name: Build desktop binaries
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-package:
    name: Build self-contained executables
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - name: Check .NET version
        run: dotnet --version
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build Windows x64 package
        run: |
          dotnet publish \
          Core/Microsoft.DataTransfer.Core/Microsoft.DataTransfer.Core.csproj \
          --configuration release \
          --output win \
          --self-contained true \
          --runtime win-x64 \
          -p:PublishSingleFile=true \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Windows x64 Cosmos Extension
        run: |
          dotnet publish \
          Extensions/Cosmos/Microsoft.DataTransfer.CosmosExtension/Microsoft.DataTransfer.CosmosExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime win-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Windows x64 JSON Extension
        run: |
          dotnet publish \
          Extensions/Json/Microsoft.DataTransfer.JsonExtension/Microsoft.DataTransfer.JsonExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime win-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Windows x64 Azure Table Extension
        run: |
          dotnet publish \
          Extensions/AzureTableAPI/Microsoft.DataTransfer.AzureTableAPIExtension/Microsoft.DataTransfer.AzureTableAPIExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime win-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Windows x64 Mongo Extension
        run: |
          dotnet publish \
          Extensions/Mongo/Microsoft.DataTransfer.MongoExtension/Microsoft.DataTransfer.MongoExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime win-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Windows x64 SQL Server Extension
        run: |
          dotnet publish \
          Extensions/SqlServer/Microsoft.DataTransfer.SqlServerExtension/Microsoft.DataTransfer.SqlServerExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime win-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Upload Windows package
        uses: actions/upload-artifact@v3
        with:
          name: windows-package
          path: win/
      - name: Build macOS x64 package
        run: |
          dotnet publish \
          Core/Microsoft.DataTransfer.Core/Microsoft.DataTransfer.Core.csproj \
          --configuration release \
          --output mac \
          --self-contained true \
          --runtime osx-x64 \
          -p:PublishSingleFile=true \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build macOS x64 Cosmos Extension
        run: |
          dotnet publish \
          Extensions/Cosmos/Microsoft.DataTransfer.CosmosExtension/Microsoft.DataTransfer.CosmosExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime osx-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build macOS x64 JSON Extension
        run: |
          dotnet publish \
          Extensions/Json/Microsoft.DataTransfer.JsonExtension/Microsoft.DataTransfer.JsonExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime osx-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build macOS x64 Azure Table Extension
        run: |
          dotnet publish \
          Extensions/AzureTableAPI/Microsoft.DataTransfer.AzureTableAPIExtension/Microsoft.DataTransfer.AzureTableAPIExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime osx-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build macOS x64 Mongo Extension
        run: |
          dotnet publish \
          Extensions/Mongo/Microsoft.DataTransfer.MongoExtension/Microsoft.DataTransfer.MongoExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime osx-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build macOS x64 SQL Server Extension
        run: |
          dotnet publish \
          Extensions/SqlServer/Microsoft.DataTransfer.SqlServerExtension/Microsoft.DataTransfer.SqlServerExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime osx-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Upload macOS package
        uses: actions/upload-artifact@v3
        with:
          name: mac-package
          path: mac/
      - name: Build Linux x64 package
        run: |
          dotnet publish \
          Core/Microsoft.DataTransfer.Core/Microsoft.DataTransfer.Core.csproj \
          --configuration release \
          --output linux \
          --self-contained true \
          --runtime linux-x64 \
          -p:PublishSingleFile=true \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Linux x64 Cosmos Extension
        run: |
          dotnet publish \
          Extensions/Cosmos/Microsoft.DataTransfer.CosmosExtension/Microsoft.DataTransfer.CosmosExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime linux-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Linux x64 JSON Extension
        run: |
          dotnet publish \
          Extensions/Json/Microsoft.DataTransfer.JsonExtension/Microsoft.DataTransfer.JsonExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime linux-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Linux x64 Azure Table Extension
        run: |
          dotnet publish \
          Extensions/AzureTableAPI/Microsoft.DataTransfer.AzureTableAPIExtension/Microsoft.DataTransfer.AzureTableAPIExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime linux-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Linux x64 Mongo Extension
        run: |
          dotnet publish \
          Extensions/Mongo/Microsoft.DataTransfer.MongoExtension/Microsoft.DataTransfer.MongoExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime linux-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Build Linux x64 SQL Server Extension
        run: |
          dotnet publish \
          Extensions/SqlServer/Microsoft.DataTransfer.SqlServerExtension/Microsoft.DataTransfer.SqlServerExtension.csproj \
          --configuration release \
          --output win/Extensions \
          --self-contained false \
          --runtime linux-x64 \
          -p:PublishSingleFile=false \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=false \
          -p:PublishTrimmed=false \
          -p:Version=0.0.${{ github.run_number }}
      - name: Upload Linux package
        uses: actions/upload-artifact@v3
        with:
          name: linux-package
          path: linux/