name: Build desktop binaries
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-package:
    name: Build self-contained executables
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - name: Check .NET version
        run: dotnet --version
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build Windows x64 package
        run: |
          dotnet publish \
          Core/Microsoft.DataTransfer.Core/Microsoft.DataTransfer.Core.csproj \
          --configuration release \
          --output win \
          --self-contained true \
          --runtime win-x64 \
          -p:PublishSingleFile=true \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=true \
          -p:PublishTrimmed=true \
          -p:Version=0.0.${{ github.run_number }} \
          -p:AssemblyName=cosmos-migrate
      - name: Upload Windows package
        uses: actions/upload-artifact@v3
        with:
          name: windows-package
          path: win/cosmos-migrate.exe
      - name: Build macOS x64 package
        run: |
          dotnet publish \
          Core/Microsoft.DataTransfer.Core/Microsoft.DataTransfer.Core.csproj \
          --configuration release \
          --output mac \
          --self-contained true \
          --runtime osx-x64 \
          -p:PublishSingleFile=true \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=true \
          -p:PublishTrimmed=true \
          -p:Version=0.0.${{ github.run_number }} \
          -p:AssemblyName=cosmos-migrate
      - name: Upload macOS package
        uses: actions/upload-artifact@v3
        with:
          name: mac-package
          path: mac/cosmos-migrate
      - name: Build Linux x64 package
        run: |
          dotnet publish \
          Core/Microsoft.DataTransfer.Core/Microsoft.DataTransfer.Core.csproj \
          --configuration release \
          --output linux \
          --self-contained true \
          --runtime linux-x64 \
          -p:PublishSingleFile=true \
          -p:DebugType=embedded \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishReadyToRun=true \
          -p:PublishTrimmed=true \
          -p:Version=0.0.${{ github.run_number }} \
          -p:AssemblyName=cosmos-migrate
      - name: Upload Linux package
        uses: actions/upload-artifact@v3
        with:
          name: linux-package
          path: linux/cosmos-migrate
