name: Build desktop binaries
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-package:
    name: Build self-contained executables
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - name: Check .NET version
        run: dotnet --version
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Execute Action build-with-plugins for Windows
        uses: ./actions/build-with-plugins
        id: build-with-plugins-win
        with:
          platform: windows
          platform-short: win
          runtime: win-x64
      - name: Execute Action build-with-plugins for MacOS
        uses: ./actions/build-with-plugins
        id: build-with-plugins-mac
        with:
          platform: mac
          platform-short: mac
          runtime: osx-x64
      - name: Execute Action build-with-plugins for Linux
        uses: ./actions/build-with-plugins
        id: build-with-plugins-linux
        with:
          platform: linux
          platform-short: linux
          runtime: linux-x64
