name: Validate all .NET projects
on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  build-test:
    name: Build and test .NET projects
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Check .NET version
        run: dotnet --version
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build project
        run: dotnet build
      - name: Run unit tests
        run: dotnet test --logger "console;verbosity=detailed"
